### ISSUE TITLE
Sign in

### ISSUE THREAD

**Issue by lishine** [ChaosGroup/redux-saga-first-router#3]
Hi,
Coming here after redux-first-router.
I like the one navigate action only.
How would implement redirect on navigate in depending if found the token in localstorage and if the route protected?
I can of course listen to navigate action, and navigate again if needed. But is this tge solution?
In rfr there is onbefore hook

**Comment by sachmata** [comment]
Hello Pavel,
I found the rfr hooks too complicated, here we have `navigateSaga` that can be registered when each route is defined and you can do your redirect there by dispatching new navigate action. Since you describe a case where probably most of your routes will be 'protected' to apply DRY principle you can have `protectedRoute` factory that returns saga to handle that.

``` js
function protectedRoute(navigateSaga) {
  return function*(...args) {
    const isAuthenticated = yield call(validateTokenFromLocalStorage)
    if(isAuthenticated) {
      yield fork(navigateSaga, ...args)
    } else {
      yield put(navigate('LOGIN'))
    }
  }
}

const routesMap = buildRoutesMap(
  route('PROJECT', '/projects/:projectName', protectedRoute(projectNavigate)),
  route('LOGIN', '/login')
  // ...
);
```

If all your 'side effects' like requesting protected data from server are initiated from saga the user will not see any protected content in the brief moment before re-navigating to 'LOGIN'.

As with this router we believe that all "business logic" should be defined in saga-s, this way we can organize our routes navigation flow without using hooks. The above `protectedRoute` can be seen as just one layer of authentication related logic that will handle if user directly lands on protected route by using bookmarked URL for example.

Hope this helps,
Cheers

**Comment by lishine** [comment]
Thanks Martin!

You answered so promptly, it is great because I can implement it now!
You fully answered all my written and not written questions! Great!
Since, I decided to implement my BL with  saga, and not in the view layer, the approach of this router exactly matches!
A few questions please:
I wander,  vs RFR:
the code of this router RSFR is simple and short, Is it really enough? It just does it's job well? Can it be used in production? Why the RFR code is so long then? And what about Link Navlink , the SEO stuff, I just l don't understand this issue yet.
Philosophically, why most of the people go in the wrong direction - like the RR and generally - put BL into view?
Seems like, RFR took approach to put route types in action types. And with RSFR the action type is just Navigate.
To me it seems more appropriate. But why do you -  think it is better?
:))
Also, I am seeking for a remote job...)

**Comment by sachmata** [comment]
I am glad to help :) On your questions:

RSFR is simple and short because it starts from brilliant idea of navigate actions of RFR and focus on minimum needed to connect browser history, redux and redux-saga. All the rest is more or less application specific and leaved to be decided by an application developer, the real power comes from 
utilizing redux-saga and route navigate saga-s. We use RSFR for over a year in our 'V-Ray Cloud' product and a few other projects, just recently we needed to add query string support. About Link and SEO stuff you can implement Link Component factory that uses your `routesMap` and exported `actionToPath` function to render links with generated href from navigate action.

``` js
function createLink(routesMap, dispatch) {
  return class Link extends React.Component {
    _onClick = e => {
      e.preventDefault();
      dispatch(this.props.to);
    }

    render() {
       return <a href={actionToPath(routesMap, this.props.to)} onClick={this._onClick}>{this.props.children}</a>
    }
  }
}
```

Philosophically :) most people don`t realize that adding redux to React changes the paradigm and popular 'good practices' found in tutorials and StackOverflow about pure React should be reevaluated, this happens once more with adding redux-saga. This might help:

https://slides.com/martindimitrov/story-from-the-trenches-react#/

Cheers

**Comment by lishine** [comment]
Great solution  for links, now I know what is seo about links :)
Great slides! Where do you use mobx? It can be used for local state as well... BTW the simplest proxy state manager react-easy-state
Interesting, you call yourself -  frontend engineer. So maybe there is no such thing as full stack. Either you are frontend, either back end, either devops, either cto or project manager :)
